<div class="page-header"><h2><?php echo $this->translate("EPM Homepage") ?></h2></div>


<div class="panel-group">
    <div class="panel panel-default c-contact-panel">
        <div class="panel-heading">
            <span class="panel-title"><?php echo $this->translate('Contact Information') ?></span>
        </div>
        <div class="panel-body c-table-heading">
            Basic Detail
        </div>
        <table class="table table-bordered table-xs hidden-lg hidden-md hidden-sm">
            <tr>
                <th class="active">
                    <span class="glyphicon glyphicon-user"></span>
                    <span class="c-label"><?php echo $this->translate('Full Name') ?></span>
                </th>
                <td>Crisdell James Ines</td>
                <th class="active">
                    <span class="glyphicon glyphicon-earphone"></span>
                    <span class="c-label"><?php echo $this->translate('Telephone') ?></span>
                </th>
                <td><span class="c-tel">63 9465856680</span></td>
            <tr>
            </tr>
            <th class="active">
                <span class="glyphicon glyphicon-globe"></span>
                <span class="c-label"><?php echo $this->translate('Language') ?></span>
            </th>
            <td>en-PH</td>
            <th class="active">
                <span class="glyphicon glyphicon-briefcase"></span>
                <span class="c-label"><?php echo $this->translate('Company') ?></span>
            </th>
            <td>ZOOP Pte Ltd.</td>
            </tr>
        </table>
        <table class="table table-striped table-condensed table-lg hidden-xs">
            <tr>
                <td class="c-label c-label-only">
                    <span class="glyphicon glyphicon-user"></span>
                </td>
                <td>Crisdell James Ines</td>
            </tr>
            <tr>
                <td class="c-label c-label-only">
                    <span class="glyphicon glyphicon-earphone"></span>
                </td>
                <td><span class="c-tel">63 9465856680</span></td>
            </tr>
            <tr>
                <td class="c-label c-label-only">
                    <span class="glyphicon glyphicon-globe"></span>
                </td>
                <td>en-PH</td>
            </tr>
            <tr>
                <td class="c-label c-label-only">
                    <span class="glyphicon glyphicon-briefcase"></span>
                </td>
                <td>ZOOP Pte Ltd.</td>
            </tr>
        </table>
    </div>
    <div class="panel-default panel">
        <div class="panel-body c-table-heading">
            More Detail
        </div>
        <table class="table table-striped table-condensed ">
            <tr>
                <td class="c-label">
                    Custom Field 1
                </td>
                <td>Value 1</td>
            </tr>
            <tr>
                <td class="c-label">
                    Custom Field 2
                </td>
                <td>Value 2</td>
            </tr>
            <tr>
                <td class="c-label">
                    Custom Field 3
                </td>
                <td>Value 13</td>
            </tr>
        </table>
    </div>
    <div class="panel-default panel">
        <div class="panel-body c-table-heading">
            Previous Attempts
        </div>
        <div class="c-history">
            <table class="table table-stripted table-condensed table-striped">
                <tr>
                    <td class="c-date">2014-10-10 23:30</td><td><span class="badge">Busy</span></td>
                </tr>
                <tr>
                    <td class="c-date">2014-10-11 19:03</td><td><span class="badge">Not in Office</span></td>
                </tr>
                <tr>
                    <td class="c-date">2014-10-12 21:04</td><td><span class="badge">Busy</span></td>
                </tr>
            </table>
        </div>
    </div>
</div>

