<div class="col-sm-4">
    <div class="panel panel-default c-panel">
        <div class="panel-heading">
            <span class="panel-title">KPI Name</span>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 c-score-box">
                    <div class="media c-kpi-detail">
                        <div class="pull-left">
                            <span class="c-score c-score-lg">88</span>
                            <span class="glyphicon glyphicon-arrow-up c-above-goal c-goal-indicator-lg"></span>
                        </div>
                        <div class="media-body">
                            <table class="table table-condensed table-striped table-bordered">
                                <tr>
                                    <th>Target</th><td></td>
                                </tr>
                                <tr>
                                    <th>MTD</th><td></td>
                                </tr>
                                <tr>
                                    <th>MTD%</th><td></td>
                                </tr>
                                <tr>
                                    <th>Pace</th><td></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <ul class="list-group">
                <li class="list-group-item">
                    <span class="label label-default c-score">1434</span> &nbsp;&nbsp;Sold Hours per RO
                </li>
                <li class="list-group-item">
                    <span class="label label-default c-score">1213</span> &nbsp;&nbsp;Shop Proficiency
                </li>
                <li class="list-group-item">
                    <span class="label label-default c-score">1213</span> &nbsp;&nbsp;Parts / Labor Ratio
                </li>
            </ul>
        </div>
    </div>
</div>